# Generated by Django 6.0.1 on 2026-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=50),
        ),
    ]
