# Generated by Django 5.1.3 on 2026-02-07 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='type',
            field=models.CharField(choices=[('courant', 'Courant'), ('epargne', 'Épargne')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
