# Generated by Django 6.0.1 on 2026-02-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banka', '0008_compte_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='banka.transaction'),
        ),
    ]
